defaults:
  - hydra: hydra

run_name: soft_voting
work_dir: ${hydra:runtime.cwd}

package_name: kaggle-ai-mathematical-olympiad-prize
connected_dir: ${oc.env:CONNECTED_DIR}/${package_name}
voted_name: soft_voting

num_labels: 1000
system: 10

voted_logit: ${connected_dir}/logits/${voted_name}
submission_file: ${connected_dir}/data/test.csv
data_column_name: problem
target_column_name: answer
voted_file: ${connected_dir}/submissions/${voted_name}.csv

votings:
  logit1: 0.5
  logit2: 0.5